# Generated by Django 4.2.5 on 2023-12-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_chapters_date_ended_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Chapters",
            new_name="Chapter",
        ),
        migrations.AddField(
            model_name="group",
            name="chapters",
            field=models.ManyToManyField(to="users.chapter"),
        ),
    ]
