# Generated by Django 4.2.5 on 2023-12-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_rename_chapters_chapter_group_chapters"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="chapter_progress",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="total_section",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
