# Generated by Django 4.2.5 on 2023-12-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_section_date_finished"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="sections",
        ),
        migrations.AddField(
            model_name="section",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.chapter",
            ),
        ),
    ]
