# Generated by Django 4.2.5 on 2024-01-18 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_chapter_options_chapter_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="section",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
