# Generated by Django 4.2.5 on 2023-11-29 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adviser", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="adviser",
        ),
        migrations.AddField(
            model_name="task",
            name="adviser",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
