# Generated by Django 4.2.5 on 2023-11-29 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adviser", "0003_remove_task_adviser_task_adviser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="adviser",
            field=models.ManyToManyField(
                blank=True, related_name="advised_tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
