# Generated by Django 4.2.5 on 2023-12-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser", "0004_alter_task_adviser"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingadvisory",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
