# Generated by Django 4.2.5 on 2023-12-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adviser", "0005_pendingadvisory_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertask",
            options={"ordering": ["task__created_at", "status"]},
        ),
        migrations.RemoveField(
            model_name="usertask",
            name="is_submitted",
        ),
        migrations.AddField(
            model_name="usertask",
            name="revised_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="usertask",
            name="status",
            field=models.CharField(default="Not Yet Submitted", max_length=255),
        ),
    ]
