# Generated by Django 4.2.5 on 2023-12-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0003_remove_capstoneapprovedtitle_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="capstoneapprovedtitle",
            name="capstone_adviser",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
