# Generated by Django 4.2.5 on 2024-01-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0004_capstoneapprovedtitle_capstone_adviser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
