# Generated by Django 4.2.5 on 2024-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("administrator", "0005_guide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="content",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
